Academic Smart Assistant: main.models.AuthPermission Class Reference
main.models.AuthPermission Class Reference
Classes
class Meta
Static Public Attributes
name = models.CharField(max_length=255)
content_type = models.ForeignKey('DjangoContentType', models.DO_NOTHING)
codename = models.CharField(max_length=100)
Member Data Documentation
codename
main.models.AuthPermission.codename = models.CharField(max_length=100) static
content_type
main.models.AuthPermission.content_type = models.ForeignKey('DjangoContentType', models.DO_NOTHING) static
name
main.models.AuthPermission.name = models.CharField(max_length=255) static
Referenced by main.models.MakereportsCollege.__str__(), main.models.MakereportsDegreeprogram.__str__(), and main.models.MakereportsDepartment.__str__().
The documentation for this class was generated from the following file:
main/models.py