Academic Smart Assistant: main.models.DjangoSummernoteAttachment Class Reference
main.models.DjangoSummernoteAttachment Class Reference
Classes
class Meta
Static Public Attributes
name = models.CharField(max_length=255, blank=True, null=True)
file = models.CharField(max_length=100)
uploaded = models.DateTimeField()
Member Data Documentation
file
main.models.DjangoSummernoteAttachment.file = models.CharField(max_length=100) static
name
main.models.DjangoSummernoteAttachment.name = models.CharField(max_length=255, blank=True, null=True) static
Referenced by main.models.MakereportsCollege.__str__(), main.models.MakereportsDegreeprogram.__str__(), and main.models.MakereportsDepartment.__str__().
uploaded
main.models.DjangoSummernoteAttachment.uploaded = models.DateTimeField() static
The documentation for this class was generated from the following file:
main/models.py